SITechnicalTest/Models/ErrorViewModel.cs
namespace SITechnicalTest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SITechnicalTest/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using SITechnicalTest.Interfaces;
using SITechnicalTest_API.Models;

namespace SITechnicalTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IWebHostEnvironment _environment;
        private readonly ISupplierService _supplierService;

        public HomeController(ILogger<HomeController> logger, IWebHostEnvironment env, ISupplierService supplierService)
        {
            _logger = logger;
            _environment = env;
            _supplierService = supplierService;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Supplier> suppliers = await _supplierService.Get();
            return View(suppliers);
        }

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Supplier());
        }

        [HttpPost]
        public async Task<IActionResult> Create(Supplier newSupplier)
        {
            bool isSuccess = await _supplierService.Create(newSupplier);
            if (isSuccess) { return RedirectToAction("Index"); }
            return View();
        }

        #endregion
        
        #region Preview

        [HttpGet]
        public async Task<IActionResult> Preview(int id)
        {
            Supplier supplier = await _supplierService.GetByID(id);
            return View(supplier);
        }

        [HttpPost]
        public IActionResult Preview()
        {
            return RedirectToAction("Index");
        }
        #endregion

        #region Update
        [HttpGet]
        public async Task<ActionResult> Update(int id)
        {
            Supplier supplier = await _supplierService.GetByID(id);
            return View(supplier);
        }

        [HttpPost]
        public async Task<ActionResult> Update(Supplier supplier)
        {
            bool isSuccess = await _supplierService.Update(supplier);
            if (isSuccess) return RedirectToAction("Index");
            return View(supplier);
        }

        #endregion

        #region Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Supplier supplier = await _supplierService.GetByID(id);
            return View(supplier);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Supplier supplier)
        {
            bool isSuccess = await _supplierService.Delete(supplier);
            if (isSuccess) return RedirectToAction("Index");
            return View(supplier);
        }

        #endregion
        
        public ActionResult ExportToCSV()
        {
            return RedirectToAction("Index", "Home");
        }

        private void WriteDataToSheet<T>(ExcelWorksheet worksheet, List<T> data)
        {
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

SITechnicalTest/Controllers/QuotationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SITechnicalTest.Interfaces;
using SITechnicalTest.Services;
using SITechnicalTest_API.Models;

namespace SITechnicalTest.Controllers
{
    public class QuotationController : Controller
    {
        private readonly IQuotationService _quotationService;
        private readonly ISupplierService _supplierService;
        public QuotationController(IQuotationService quotationService, ISupplierService supplierService)
        {
            _supplierService = supplierService;
            _quotationService = quotationService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Quotation> quotations = await _quotationService.Get();
            return View(quotations);
        }
        #region Create
        [HttpGet]
        public async Task<IActionResult> CreateQuotation()
        {
            List<Supplier> suppliers = await _supplierService.Get();
            ViewBag.Suppliers = suppliers;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateQuotation(Quotation newQuotation)
        {
            bool isSuccess = await _quotationService.Create(newQuotation);
            if (isSuccess) { return RedirectToAction("Index"); }
            return View();
        }
        #endregion

        #region Preview
        [HttpGet]
        public async Task<IActionResult> Preview(int QuotationId)
        {
            Quotation quotation = await _quotationService.GetByID(QuotationId);
            return View(quotation);
        }
        #endregion

        #region Update
        [HttpGet]
        public async Task<IActionResult> Edit(int QuotationId)
        {
            Quotation quotation = await _quotationService.GetByID(QuotationId);
            ViewBag.Suppliers = await _supplierService.Get();
            return View(quotation);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Quotation updatedQuotation)
        {
            bool isSuccess = await _quotationService.Update(updatedQuotation);
            if (isSuccess) return RedirectToAction("Index");
            return View(updatedQuotation);
        }

        #endregion

        #region Delete
        [HttpGet]
        public async Task<IActionResult> Remove(int QuotationId)
        {
            Quotation quotation = await _quotationService.GetByID(QuotationId);
            return View(quotation);
        }

        [HttpPost]
        public async Task<IActionResult> Remove(Quotation toBeRemovedQuotation)
        {
            bool isSuccess = await _quotationService.Delete(toBeRemovedQuotation);
            if (isSuccess) return RedirectToAction("Index");
            return View(toBeRemovedQuotation);
        } 
        #endregion
    }
}

SITechnicalTest/Views/Home/Create.cshtml
@model Supplier

@{
    if (Model.DateCreated == DateTime.MinValue || Model.DateCreated == null)
    {
        Model.DateCreated = DateTime.Today;
    }
}

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Create Supplier
            </h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0"></label>
            <input asp-for="Name" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Email" class="p-0"></label>
            <input asp-for="Email" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="CountryCode" class="p-0"></label>
            <input asp-for="CountryCode" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="DateCreated" class="p-0"></label>
            <input asp-for="DateCreated" class="form-control" type="date" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>
        </div>

    </div>
</form>

SITechnicalTest/Views/Home/Delete.cshtml
@model DbSupplier


<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Delete Supplier
            </h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0"></label>
            <input disabled asp-for="Name" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Email" class="p-0"></label>
            <input disabled asp-for="Email" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="CountryCode" class="p-0"></label>
            <input disabled asp-for="CountryCode" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="DateCreated" class="p-0"></label>
            <input disabled asp-for="DateCreated" class="form-control" type="date" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Delete</button>
            </div>
        </div>
    </div>

</form>

SITechnicalTest/Views/Home/Index.cshtml
@model List<Supplier> 
<div>
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Supplier List</h2>
        </div>
        <div class="col-6 text-end p-4">
            <a asp-controller="Home" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Create
            </a>
            <a asp-controller="Home" asp-action="ExportToCSV" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Export
            </a>
        </div>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Country</th>
                <th>DateCreated</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model.OrderByDescending(a => a.Name).OrderByDescending(c => c.DateCreated).OrderBy(x => x.CountryCode))
            {
                <tr>
                    <td>@obj.Id</td>
                    <td>@obj.Name</td>
                    <td>@obj.Email</td>
                    <td>@obj.CountryCode</td>
                    <td>@obj.DateCreated.ToString("dd-MMM-yyyy")</td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Home" asp-action="Preview" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                <span>View</span>
                            </a>
                        </div>
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Home" asp-action="Update" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                <span>Update</span>
                            </a> 
                        </div>
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Home" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                <span>Delete</span>
                            </a>
                        </div>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

SITechnicalTest/Views/Home/Preview.cshtml
@model Supplier

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Preview Supplier
            </h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0"></label>
            <input disabled asp-for="Name" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Email" class="p-0"></label>
            <input disabled asp-for="Email" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="CountryCode" class="p-0"></label>
            <input disabled asp-for="CountryCode" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="DateCreated" class="p-0"></label>
            <input disabled asp-for="DateCreated" class="form-control" type="date" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Back</button>
            </div>
        </div>
    </div>

</form>

SITechnicalTest/Views/Home/Update.cshtml
@model Supplier


<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Update Supplier
            </h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0"></label>
            <input asp-for="Name" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Email" class="p-0"></label>
            <input asp-for="Email" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="CountryCode" class="p-0"></label>
            <input asp-for="CountryCode" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="DateCreated" class="p-0"></label>
            <input asp-for="DateCreated" class="form-control" type="date" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
        </div>
    </div>

</form> 

SITechnicalTest/Views/Quotation/Create.cshtml
@* @model CompositeSupplierQuotation

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Create Quotation
            </h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label for="SupplierId" class="p-0">Supplier</label>
            <select asp-for="Quotation.SupplierId" asp-items="Model.Suppliers.Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Name })" class="form-control">
                <option value="">Select Supplier</option>
            </select>
            <span asp-validation-for="Quotation.SupplierId" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Quotation.Product" class="p-0"></label>
            <input asp-for="Quotation.Product" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Quotation.CostPerUnit" class="p-0"></label>
            <input asp-for="Quotation.CostPerUnit" class="form-control" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Home" asp-action="Index" class="btn btn-outline-secondary form-control">Back</a>
            </div>
        </div>


    </div>
</form> *@

SITechnicalTest/Views/Quotation/CreateQuotation.cshtml
@model Quotation

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Create Quotation
            </h2>
            <hr />
        </div>

         <div class="mb-3 row p-1">
            <label for="SupplierId" class="p-0">Supplier</label>
            <select asp-for="SupplierId" class="form-control">
                <option value="">Select Supplier</option>
                @foreach(Supplier supplier in ViewBag.Suppliers)
                {
                    <option value="@supplier.Id">@supplier.Id - @supplier.Name</option>
                }
            </select>
            <span asp-validation-for="SupplierId" class="text-danger"></span>
        </div>
 
        <div class="mb-3 row p-1">
            <label asp-for="Product" class="p-0"></label>
            <input asp-for="Product" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="CostPerUnit" class="p-0"></label>
            <input asp-for="CostPerUnit" class="form-control" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Home" asp-action="Index" class="btn btn-outline-secondary form-control">Back</a>
            </div>
        </div>


    </div>
</form>  

SITechnicalTest/Views/Quotation/Delete.cshtml
@* @model CompositeSupplierQuotation


<form method="post">
    <input asp-for="Quotation.QuotationId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Delete Quotation
            </h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label for="SupplierId" class="p-0">Supplier</label>
            <select disabled asp-for="Quotation.SupplierId" asp-items="Model.Suppliers.Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Name })" class="form-control">
                <option value="">Select Supplier</option>
            </select>
            <span asp-validation-for="Quotation.SupplierId" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Quotation.Product" class="p-0"></label>
            <input disabled asp-for="Quotation.Product" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Quotation.CostPerUnit" class="p-0"></label>
            <input disabled asp-for="Quotation.CostPerUnit" class="form-control" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-danger form-control">Delete</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Quotation" asp-action="Index" class="btn btn-outline-secondary form-control">Back</a>
            </div>
        </div>
    </div>

</form>
 *@

SITechnicalTest/Views/Quotation/Edit.cshtml
@model Quotation


<form method="post">
    <input asp-for="QuotationId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Update Quotation @Model.QuotationId
            </h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <select asp-for="SupplierId" class="form-control">
                <option value="">Select Supplier</option>
                @foreach (Supplier supplier in ViewBag.Suppliers)
                {
                    <option value="@supplier.Id">@supplier.Id - @supplier.Name</option>
                }
            </select>
            <span asp-validation-for="SupplierId" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Product" class="p-0"></label>
            <input asp-for="Product" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="CostPerUnit" class="p-0"></label>
            <input asp-for="CostPerUnit" class="form-control" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Quotation" asp-action="Index" class="btn btn-outline-secondary form-control">Back</a>
            </div>
        </div>
    </div>

</form>

SITechnicalTest/Views/Quotation/Index.cshtml
@model List<Quotation>
<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Quotation List</h2>
        </div>
        <div class="col-6 text-end p-4">
            <a asp-controller="Quotation" asp-action="CreateQuotation" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Create
            </a>
        </div>
    </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Supplier Name</th>
                <th>Products</th>
            </tr>
        </thead>
        <tbody>
            @{
                var groupQuotation = Model.GroupBy(x => x.SupplierId);
            }
            @foreach (var group in groupQuotation)
            {
                var items = group.OrderByDescending(x => x.SupplierId).OrderBy(a => a.Product);

                foreach(Quotation item in items)
                {
                    <tr>
                        @if(item == items.First())
                        {
                            <td rowspan="@group.Count()">@group.First().Supplier?.Name</td>
                        }
                        @if(item.CostPerUnit != null)
                        {
                            <td>
                                @item.Product: $@item.CostPerUnit
                                <a asp-controller="Quotation" asp-action="Preview" asp-route-QuotationId="@item.QuotationId" class="btn btn-primary mx-2">
                                    <span>Show</span>
                                </a>
                                <a asp-controller="Quotation" asp-action="Edit" asp-route-QuotationId="@item.QuotationId" class="btn btn-primary mx-2">
                                    <span>Edit</span>
                                </a>
                                <a asp-controller="Quotation" asp-action="Remove" asp-route-QuotationId="@item.QuotationId" class="btn btn-primary mx-2">
                                    <span>Delete</span>
                                </a>
                            </td>
                        }
                    </tr>
                }
            }
            
        </tbody>
    </table> 
</div>

SITechnicalTest/Views/Quotation/Preview.cshtml
@model Quotation


<form method="post">
    <input asp-for="QuotationId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Quotation @Model.QuotationId
            </h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label for="SupplierId" class="p-0">Supplier</label>
            <select disabled asp-for="SupplierId" class="form-control">
                <option value="">@Model.SupplierId</option>
            </select>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Product" class="p-0"></label>
            <input disabled asp-for="Product" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="CostPerUnit" class="p-0"></label>
            <input disabled asp-for="CostPerUnit" class="form-control" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <a asp-controller="Quotation" asp-action="Index" class="btn btn-outline-secondary form-control">Back</a>
            </div>
        </div>
    </div>

</form>
 

SITechnicalTest/Views/Quotation/Remove.cshtml
@model Quotation


<form method="post">
    <input asp-for="QuotationId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Quotation @Model.QuotationId
            </h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label for="SupplierId" class="p-0">Supplier</label>
            <select disabled asp-for="SupplierId" class="form-control">
                <option value="">@Model.SupplierId</option>
            </select>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Product" class="p-0"></label>
            <input disabled asp-for="Product" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="CostPerUnit" class="p-0"></label>
            <input disabled asp-for="CostPerUnit" class="form-control" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-danger form-control">Delete</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Quotation" asp-action="Index" class="btn btn-outline-secondary form-control">Back</a>
            </div>
        </div>
    </div>

</form>

SITechnicalTest/Views/Quotation/Update.cshtml
@model Quotation


<form method="post">
    <input asp-for="QuotationId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Update Quotation @Model.QuotationId
            </h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <select asp-for="SupplierId" class="form-control">
                <option value="">Select Supplier</option>
                @foreach (Supplier supplier in ViewBag.Suppliers)
                {
                    <option value="@supplier.Id">@supplier.Id - @supplier.Name</option>
                }
            </select>
            <span asp-validation-for="SupplierId" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Product" class="p-0"></label>
            <input asp-for="Product" class="form-control" />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="CostPerUnit" class="p-0"></label>
            <input asp-for="CostPerUnit" class="form-control" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Quotation" asp-action="Index" class="btn btn-outline-secondary form-control">Back</a>
            </div>
        </div>
    </div>

</form>

SITechnicalTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SITechnicalTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SITechnicalTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SITechnicalTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quotation" asp-action="Index">Quotation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SITechnicalTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>